# Minimal, safe defaults
seed: 1337

dataset:
  n_train: 8000
  n_val: 2000
  n_features: 20
  n_classes: 3
  noise_std: 0.8

model:
  hidden_sizes: [64, 64]   # keep it small
  activation: relu         # relu or gelu

train:
  batch_size: 256
  epochs: 8
  lr: 0.001
  weight_decay: 0.0

system:
  precision: fp32          # fp32 | bf16 | fp16 (GPU only for mixed precision)
  num_workers: 0           # 0 is simplest + deterministic for beginners
  deterministic: true      # try to keep runs repeatable
  device: auto             # auto | cpu | cuda
